database:
  database: taxidb
  host: localhost
  port: 5432
  username: postgres
  password: postgres
url: https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv
fname: rides.csv
period:
  start_date: '2021-01-01'
  end_date: '2021-01-02'
columns:
- pickup_datetime
- dropoff_datetime
- pickup_latitude
- pickup_longitude
- dropoff_latitude
- dropoff_longitude
- passenger_count
- total_amount
- payment_type
- rate_code
