database:
  database: Environmental_Analytics
  host: localhost
  port: 5432
  username: postgres
  password: novaims
url: http://opendata-cml.qart.pt/lastmeasurements
fname_stations: stations_lisbon.geojson
fname_fraguesias: fraguesias.geojson
fname_report: Env_Lisbon_report.pdf
